### ISSUE TITLE
Doesn't work on windows

### ISSUE THREAD

**Issue by maniac-en** [holmes-py/subdomain-check#2]
#### It just iterates infinitely!

**Steps to reproduce:**

> 1. changed fileformat from `dos` to `unix`
> 2. `cat test.txt`
> ```
> nwk-aaemail-lapp03.apple.com
> a.ns.apple.com
> ma1-aaemail-dr-lapp01.apple.com
> d.ns.apple.com
> c.ns.apple.com
> ma1-aaemail-dr-lapp02.apple.com
> b.ns.apple.com
> ma1-aaemail-dr-lapp03.apple.com
> ```
> 3. `./Subdomain-check-v1.py test.txt`
> Following images show the same:
> ### [Image 1](https://imgur.com/1ey1tdf)
> ![image](https://user-images.githubusercontent.com/45049766/83937439-33b66a00-a7ea-11ea-9b19-047f066cd7b2.png)
> ### [Image 2](https://imgur.com/zMtZyUI)
> ![image](https://user-images.githubusercontent.com/45049766/83937412-f05bfb80-a7e9-11ea-8972-1044080342ea.png)

#### Please look into it!, Thankyou!

**Comment by holmes-py** [comment]
Never intended for it to run in windows. My bad, should've mentioned it. 
Anyway, I'll look into it.
:v:
